### ISSUE TITLE
Removes all "/" forward slash character from comments

### ISSUE THREAD

**Issue by dejanjankovic** [markwpearce/brighterscript-jsdocs-plugin#4]
https://github.com/markwpearce/brighterscript-jsdocs-plugin/blob/3a30ca5b92f74d724ec0a6f69afc3ae375b13d1f/convert-brighterscript-docs.js#L169
This regex will find any "/" forward slash in the line and replace it with "". It is not counting in the "*" character from regex and it will match even single forwards slash. This means that it will strip all "/" from comments, even HTML closing tags. 

![image](https://user-images.githubusercontent.com/4817479/145980257-beeb830f-fd9a-4ce4-b2d9-3179254f2bb8.png)

**Comment by markwpearce** [comment]
Great catch! Thanks. I'll update it soon!
