### ISSUE TITLE
[feature request] [please add support for enums and interfaces

### ISSUE THREAD

**Issue by ZeeD** [markwpearce/brighterscript-jsdocs-plugin#6]
first of all, thank you for the plugin, I find it very useful to generate some API documentation

brighterscript support both [enums](https://github.com/rokucommunity/brighterscript/blob/master/docs/enums.md) and [interfaces](https://github.com/rokucommunity/brighterscript/discussions/671)

it would be cool if this plugin could add support for these two constructs

**Comment by markwpearce** [comment]
I realize this is almost 2 years old now, but I'm currently working on this

**Comment by markwpearce** [comment]
done as of 0.7.0
